import { editor } from 'monaco-editor';

export const DarkTheme: editor.IStandaloneThemeData = {
    base: 'vs-dark',
    inherit: true,
    colors: {
        'editor.background': '#1E1E1E',
        'editor.foreground': '#D4D4D4',
        'editor.inactiveSelectionBackground': '#3A3D41',
        'editorIndentGuide.background': '#404040',
        'editorIndentGuide.activeBackground': '#707070',
        'editor.selectionHighlightBackground': '#ADD6FF26',
        'list.dropBackground': '#383B3D',
        'activityBarBadge.background': '#007ACC',
        'sideBarTitle.foreground': '#BBBBBB',
        'input.placeholderForeground': '#A6A6A6',
        'settings.textInputBackground': '#292929',
        'settings.numberInputBackground': '#292929',
        'menu.background': '#252526',
        'menu.foreground': '#CCCCCC',
        'statusBarItem.remoteForeground': '#FFF',
        'statusBarItem.remoteBackground': '#16825D',
        'sideBarSectionHeader.background': '#0000',
        'sideBarSectionHeader.border': '#ccc3',
    },
    rules: [
        { token: 'plainKeyword', foreground: '#569cd6' },
        { token: 'class', foreground: '#4EC9B0' },
        { token: 'struct', foreground: '#86c691' },

        { token: 'regexp', foreground: '#d16969' },
        { token: 'excludedCode', foreground: '#808080' },
        { token: 'preprocessorKeyword', foreground: '#808080' },
        { token: 'preprocessorText', foreground: '#FFFFFF' },
        { token: 'punctuation', foreground: '#D4D4D4' },
        { token: 'string', foreground: '#ce9178' },
        { token: 'namespace', foreground: '#D4D4D4' },
        { token: 'field', foreground: '#D4D4D4' },
        { token: 'property', foreground: '#D4D4D4' },
        { token: 'constant', foreground: '#D4D4D4' },
        { token: 'enumMember', foreground: '#D4D4D4' },
        { token: 'interface', foreground: '#b8d7a3' },
        { token: 'enum', foreground: '#b8d7a3' },
        { token: 'parameter', foreground: '#9CDCFE' },
        { token: 'typeParameter', foreground: '#b8d7a3' },
        { token: 'extension', foreground: '#DCDCAA' },
        { token: 'documentation', foreground: '#608B4E' },
        { token: 'attribute', foreground: '#C8C8C8' },
        { token: 'cdata', foreground: '#E9D585' },
        { token: 'controlKeyword', foreground: '#c586c0' },
        { token: 'stringEscapeCharacter', foreground: '#d7ba7d' },
        { token: 'member', foreground: '#DCDCAA' },
        { token: 'extensionMethod', foreground: '#DCDCAA' },
        { token: 'variable', foreground: '#D4D4D4' },
        { token: 'delegate', foreground: '#4EC9B0' },
        { token: 'xmlDocCommentText', foreground: '#608B4E' },
        { token: 'xmlDocCommentDelimiter', foreground: '#608B4E' },
        { token: 'xmlDocCommentName', foreground: '#608B4E' },
        { token: 'string', foreground: '#ce9178' },
        { token: 'stringVerbatim', foreground: '#ce9178' },
    ],
};

export const LightTheme: editor.IStandaloneThemeData = {
    base: 'vs',
    inherit: true,
    colors: {},
    rules: [
        { token: 'plainKeyword', foreground: '#0000ff' },
        { token: 'class', foreground: '#0db8ea' },
        { token: 'struct', foreground: '#0db8ea' },

        { token: 'regexp', foreground: '#811f3f' },
        { token: 'excludedCode', foreground: '#808080' },
        { token: 'preprocessorKeyword', foreground: '#808080' },
        { token: 'preprocessorText', foreground: '#D4D4D4' },
        { token: 'punctuation', foreground: '#222222' },
        { token: 'string', foreground: '#a31515' },
        { token: 'namespace', foreground: '#222222' },
        { token: 'field', foreground: '#222222' },
        { token: 'property', foreground: '#222222' },
        { token: 'constant', foreground: '#222222' },
        { token: 'enumMember', foreground: '#222222' },
        { token: 'interface', foreground: '#0db8ea' },
        { token: 'enum', foreground: '#0db8ea' },
        { token: 'parameter', foreground: '#222222' },
        { token: 'typeParameter', foreground: '#4EC9B0' },
        { token: 'extension', foreground: '#222222' },
        { token: 'documentation', foreground: '#008000' },
        { token: 'attribute', foreground: '#282828' },
        { token: 'cdata', foreground: '#808080' },
        { token: 'controlKeyword', foreground: '#AF00DB' },
        { token: 'stringEscapeCharacter', foreground: '#ff0000' },
        { token: 'member', foreground: '#222222' },
        { token: 'extensionMethod', foreground: '#222222' },
        { token: 'variable', foreground: '#222222' },
        { token: 'delegate', foreground: '#0db8ea' },
        { token: 'xmlDocCommentText', foreground: '#008000' },
        { token: 'xmlDocCommentDelimiter', foreground: '#008000' },
        { token: 'xmlDocCommentName', foreground: '#008000' },
        { token: 'string', foreground: '#a31515' },
        { token: 'stringVerbatim', foreground: '#a31515' },
    ],
};
