export enum SemanticTokenTypes {
    comment = 'comment',
    keyword = 'keyword',
    string = 'string',
    number = 'number',
    regexp = 'regexp',
    operator = 'operator',
    namespace = 'namespace',
    type = 'type',
    struct = 'struct',
    class = 'class',
    interface = 'interface',
    enum = 'enum',
    typeParameter = 'typeParameter',
    function = 'function',
    member = 'member',
    property = 'property',
    macro = 'macro',
    variable = 'variable',
    parameter = 'parameter',
    label = 'label',
}

export enum SemanticTokenModifiers {
    documentation = 'documentation',
    declaration = 'declaration',
    definition = 'definition',
    reference = 'reference',
    static = 'static',
    abstract = 'abstract',
    deprecated = 'deprecated',
    async = 'async',
    volatile = 'volatile',
    readonly = 'readonly',
}
